### ISSUE TITLE
Bug: two progress bars in one component

### ISSUE THREAD

**Issue by KevKo1990** [oblador/react-native-progress#62] opened 2017-06-29 04:22 UTC
We updated our react native to version 0.44.3 and since then, we have strange problems on Android (iOS works fine).

In our component, we have a "time bar" and a "point bar".
There are two major problems:
- we I give a default e.g. just to the time progress bar... both change accordingly to the time progress bar value...
- With 0, the bar is completely full (0 should be empty), with a fixed value of 0.0001 it is empty...

**default value 0:**
![27621951-3c8fd60e-5c0f-11e7-8152-28a002dbf74c](https://user-images.githubusercontent.com/12497609/27671302-db7f8e80-5ccd-11e7-8242-9aa853ce251d.png)

**fixed value of 0.5 in the time bar:**
![screenshot_1498708989](https://user-images.githubusercontent.com/12497609/27671303-db94b17a-5ccd-11e7-978c-42e1be706624.png)

**Comment by oblador** [comment] 2017-07-03 21:37
Hi, this sounds like a react-native core bug. I couldn't reproduce on 0.45.1 with `<Progress.Bar progress={0} />`, are you still seeing this? If so can you give me some code to reproduce this error?

**Comment by oblador** [comment] 2017-07-03 23:02
Closing due to duplicate of https://github.com/oblador/react-native-progress/issues/56

**Closed by oblador** 2017-07-03 23:02 UTC
