### ISSUE TITLE
Incorrect position

### ISSUE THREAD

**Issue by yutin1987** [oblador/react-native-progress#17] opened 2016-07-26 12:27 UTC
https://youtu.be/pwe0b6H1xoE

**Comment by yutin1987** [comment] 2016-07-26 12:30
maybe, can setting transform-origin in the feature.
https://github.com/facebook/react-native/issues/1964

fixed it, add `{width, height}` into https://github.com/oblador/react-native-progress/blob/master/makeAnimatable.js#L103

**Comment by chirag04** [comment] 2016-08-10 16:44
@oblador I can confirm the same behavior.

**Comment by chirag04** [comment] 2016-08-10 16:51
ok this is duplicate of https://github.com/oblador/react-native-progress/issues/11

**Comment by oblador** [comment] 2017-07-03 22:54
Closing duplicate

**Closed by oblador** 2017-07-03 22:54 UTC
