### ISSUE TITLE
Android issue when progress is 0

### ISSUE THREAD

**Issue by zoranmarjanovic** [oblador/react-native-progress#58] opened 2017-05-30 07:46 UTC
There is an issue in android when progress value is 0, because of react-native issue when transform scaleX value is 0. The workaround would be to set progress to 0.001 value, it would be great if you put that in documentation.

**Comment by DemisBand** [comment] 2017-06-21 14:01
+1

**Comment by oblador** [comment] 2017-07-03 21:39
Is this still a problem in react native 0.45.1? I cannot reproduce myself.

**Comment by oblador** [comment] 2017-07-03 23:02
Anyway, duplicate of https://github.com/oblador/react-native-progress/issues/56

**Closed by oblador** 2017-07-03 23:02 UTC
